-- db-work-queue engine schema (spec §4). Applied by the migrate job only; workers never run DDL.
-- Requires the Flyway placeholder workqueueNamespace: this queue's namespace (spec §5.4).

CREATE TABLE WORK_QUEUE_META (
    NAMESPACE VARCHAR(32) NOT NULL,
    CONSTRAINT CK_WORK_QUEUE_META_NAMESPACE CHECK (LENGTH(NAMESPACE) >= 1 AND LOCATE(':', NAMESPACE) = 0)
);

INSERT INTO WORK_QUEUE_META (NAMESPACE) VALUES ('${workqueueNamespace}');

CREATE TABLE WORK_ITEM (
    ID           BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY,
    OPERATION_ID VARCHAR(64)   NOT NULL,
    PAYLOAD      VARCHAR(1000) NOT NULL,
    STATUS       VARCHAR(10)   NOT NULL DEFAULT 'PENDING',
    AVAILABLE_AT TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    OWNER        VARCHAR(64),
    CLAIM_TOKEN  BIGINT        NOT NULL DEFAULT 0,
    ATTEMPTS     INTEGER       NOT NULL DEFAULT 0,
    RESULT_VALUE VARCHAR(1000),
    LAST_ERROR   VARCHAR(1000),
    CREATED_AT   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_WORK_ITEM PRIMARY KEY (ID),
    CONSTRAINT UQ_WORK_ITEM_OPERATION_ID UNIQUE (OPERATION_ID),
    CONSTRAINT CK_WORK_ITEM_STATUS CHECK (STATUS IN ('PENDING', 'CLAIMED', 'DONE', 'FAILED'))
);

CREATE INDEX IX_WORK_ITEM_CLAIM ON WORK_ITEM (STATUS, AVAILABLE_AT);
